# Generated by Django 5.2.8 on 2025-11-16 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('size_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('crops', 'Crops'), ('livestock', 'Livestock'), ('poultry', 'Poultry'), ('aquaculture', 'Aquaculture'), ('horticulture', 'Horticulture'), ('mixed', 'Mixed Farming')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_planted', models.DecimalField(decimal_places=2, help_text='In kg or units', max_digits=10)),
                ('quantity_harvested', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farms.farm')),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='FarmProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('crops', 'Crops'), ('livestock', 'Livestock'), ('poultry', 'Poultry'), ('aquaculture', 'Aquaculture'), ('horticulture', 'Horticulture'), ('mixed', 'Mixed Farming')], max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(help_text='e.g., Goats, Cattle, Sheep, Pigs', max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('tag_number', models.CharField(help_text='Unique identifier', max_length=50, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('quarantine', 'Quarantine'), ('deceased', 'Deceased')], default='healthy', max_length=20)),
                ('purpose', models.CharField(blank=True, choices=[('meat', 'Meat Production'), ('dairy', 'Dairy Production'), ('breeding', 'Breeding'), ('sale', 'For Sale')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='farms.farm')),
            ],
            options={
                'verbose_name_plural': 'Livestock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopulationStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('date_recorded', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_stats', to='farms.farm')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
